import type { Metadata } from "next";
import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";
import AboutPage from "@/components/LatestBlogs";
import BrowseGenres from "@/components/BrowseGenres";
import WhyChoose from "@/components/WhyChoose";
import FeaturedCollections from "@/components/FeaturedCollections";
import Testimonials from "@/components/Testimonials";
import Statistics from "@/components/FAQ";
import FAQ from "@/components/FAQ";
import CTA from "@/components/LatestBlogs";
import LatestBlogs from "@/components/LatestBlogs";
import StreamingPlatforms from "@/components/StreamingPlatforms";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas",
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bebasNeue.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <Hero/>
        <BrowseGenres/>
        <WhyChoose/>
        <FeaturedCollections/>
        <StreamingPlatforms/>
        <Testimonials/>
        <FAQ/>
        <LatestBlogs/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
